---
- name: Configure web server
  hosts: all
  become: yes
  tasks:
    - name: Install NGINX
      yum:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Add Hello World HTML page
      copy:
        content: "<html><body><h1>Hello, World!</h1></body></html>"
        dest: /usr/share/nginx/html/indel.html
        mode: '0644'
