---

- name: Update all packages and install Ansible
  hosts: all
  become: yes
  tasks:
    - name: Run yum update
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Enable EPEL repository (required for Ansible on Amazon Linux 2)
      amazon.aws.amazon_linux_extras:
        name: epel
        state: enabled
      when: ansible_distribution == "Amazon"

    - name: Install Ansible
      yum:
        name: ansible
        state: present
  tasks:
    - name: Install NGINX
      yum:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Add Hello World HTML page
      copy:
        content: "<html><body><h1>Hello, World!</h1></body></html>"
        dest: /usr/share/nginx/html/index.html
        mode: '0644'
